### ISSUE TITLE
Any possible alternatives to Coilcraft DA2032-ALB?

### ISSUE THREAD

**Issue by Fxlr8** [tonyp7/170v-nixie-power-supply#1]
Hi, Tony, thanks for a great design. I want to use it in my project, but those coils are rather exotic. Сompanies like JLCPCB or LCSC just don't have it. Can it be replaced with something more popular?

**Comment by tonyp7** [comment]
You can replace it but you'll need a 1:10 ~10uH transformer.

They are not very common and some other parts you may find typically are wired in reverse (that is to say they are more a 10:1 transformer and can't handle the high current on the low side)

There are importunately no such thing as "popular part" when it comes to transformers.

**Comment by Fxlr8** [comment]
Ok, got it. I think I will order Coilcraft's transformers then. Want to be 100% sure that everything works as expected.
